use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Profile {
    /// Unique identifier
    pub id: String,
    /// Display name
    pub name: String,
    /// Description of the profile
    pub description: String,
    /// Color hex for UI display
    pub color: String,
    /// Ordered list of skill IDs in this profile
    pub skill_ids: Vec<String>,
    /// Whether this is a built-in preset
    pub is_preset: bool,
}

impl Profile {
    pub fn presets() -> Vec<Profile> {
        vec![
            Profile {
                id: "preset-java".into(),
                name: "Java 开发".into(),
                description: "Java/Maven 项目开发全流程".into(),
                color: "#d4a259".into(),
                skill_ids: vec![
                    "maven-operating".into(),
                    "code-review".into(),
                    "unit-test-gen".into(),
                    "java-project-ai-prompt-init".into(),
                    "designing-database-tables".into(),
                    "troubleshooting-java-logs".into(),
                    "git-committing".into(),
                    "deploy-test".into(),
                    "java-multimodule-keyword-replacement".into(),
                    "flowchart-gen".into(),
                    "api-doc-gen".into(),
                    "java-requirement-development".into(),
                    "developing-from-product-docs".into(),
                    "fetching-prd-from-gitlab".into(),
                ],
                is_preset: true,
            },
            Profile {
                id: "preset-workflow".into(),
                name: "通用工作流".into(),
                description: "代码审查、Git、计划、调试等通用流程".into(),
                color: "#3B82F6".into(),
                skill_ids: vec![
                    "brainstorming".into(),
                    "writing-plans".into(),
                    "executing-plans".into(),
                    "code-review-plus".into(),
                    "git-committing".into(),
                    "systematic-debugging".into(),
                    "test-driven-development".into(),
                    "verification-before-completion".into(),
                    "dispatching-parallel-agents".into(),
                    "subagent-driven-development".into(),
                    "finishing-a-development-branch".into(),
                    "requesting-code-review".into(),
                    "using-git-worktrees".into(),
                ],
                is_preset: true,
            },
            Profile {
                id: "preset-marketing".into(),
                name: "营销增长".into(),
                description: "营销内容、品牌、竞品分析、SEO".into(),
                color: "#EC4899".into(),
                skill_ids: vec![
                    "example-skills:frontend-design".into(),
                    "example-skills:brand-guidelines".into(),
                    "example-skills:canvas-design".into(),
                    "example-skills:web-artifacts-builder".into(),
                    "quality-website-search".into(),
                    "rss-daily-digest".into(),
                    "marketingskills/skills/seo-audit".into(),
                    "marketingskills/skills/copywriting".into(),
                    "marketingskills/skills/content-strategy".into(),
                    "marketingskills/skills/social-content".into(),
                    "marketingskills/skills/competitor-alternatives".into(),
                    "ui-reference-to-code".into(),
                ],
                is_preset: true,
            },
            Profile {
                id: "preset-devops".into(),
                name: "DevOps".into(),
                description: "Docker、部署、服务器运维".into(),
                color: "#10B981".into(),
                skill_ids: vec![
                    "docker-bluegreen-deploy".into(),
                    "deploy-test".into(),
                    "aliyun-init".into(),
                    "maven-operating".into(),
                    "git-committing".into(),
                    "linux-server-bootstrap".into(),
                    "example-skills:mcp-builder".into(),
                ],
                is_preset: true,
            },
            Profile {
                id: "preset-frontend".into(),
                name: "前端工程开发".into(),
                description: "前端 UI 开发、H5、React、Next.js、部署".into(),
                color: "#f2994a".into(),
                skill_ids: vec![
                    "example-skills:frontend-design".into(),
                    "example-skills:web-artifacts-builder".into(),
                    "example-skills:webapp-testing".into(),
                    "ui-reference-to-code".into(),
                    "linear-dark-ui-style".into(),
                    "nextjs-migration".into(),
                    "deploy-to-vercel".into(),
                    "fenxiang-skills/frontend/skills/h5-development-standards".into(),
                    "fenxiang-skills/frontend/skills/converting-ui-to-h5code".into(),
                    "fenxiang-skills/frontend/skills/implementing-complex-ui-pages".into(),
                    "fenxiang-skills/frontend/skills/react-mobile-h5-activity-page".into(),
                    "fenxiang-skills/frontend/skills/ordering-tailwind-classes".into(),
                    "brainstorming".into(),
                    "code-review-plus".into(),
                    "git-committing".into(),
                ],
                is_preset: true,
            },
            Profile {
                id: "preset-media-content".into(),
                name: "自媒内容创作".into(),
                description: "AI 生图、文章配图、自媒体发布（微信/X/小红书）".into(),
                color: "#a77bca".into(),
                skill_ids: vec![
                    "baoyu-skills/skills/baoyu-image-gen".into(),
                    "baoyu-skills/skills/baoyu-article-illustrator".into(),
                    "baoyu-skills/skills/baoyu-infographic".into(),
                    "baoyu-skills/skills/baoyu-cover-image".into(),
                    "baoyu-skills/skills/baoyu-comic".into(),
                    "baoyu-skills/skills/baoyu-xhs-images".into(),
                    "baoyu-skills/skills/baoyu-post-to-wechat".into(),
                    "baoyu-skills/skills/baoyu-post-to-x".into(),
                    "baoyu-skills/skills/baoyu-url-to-markdown".into(),
                    "baoyu-skills/skills/baoyu-format-markdown".into(),
                    "example-skills:canvas-design".into(),
                    "example-skills:algorithmic-art".into(),
                    "video-downloader".into(),
                    "transcript-summarizer".into(),
                ],
                is_preset: true,
            },
            Profile {
                id: "preset-office-content".into(),
                name: "办公内容创作".into(),
                description: "文档、PPT、表格、会议纪要、周报".into(),
                color: "#7c8ea6".into(),
                skill_ids: vec![
                    "example-skills:pptx".into(),
                    "example-skills:pdf".into(),
                    "example-skills:docx".into(),
                    "example-skills:xlsx".into(),
                    "example-skills:doc-coauthoring".into(),
                    "example-skills:internal-comms".into(),
                    "example-skills:theme-factory".into(),
                    "baoyu-skills/skills/baoyu-slide-deck".into(),
                    "baoyu-skills/skills/baoyu-format-markdown".into(),
                    "NanoBanana-PPT-Skills".into(),
                    "meeting-minutes".into(),
                    "weekly-report".into(),
                    "transcript-summarizer".into(),
                ],
                is_preset: true,
            },
            Profile {
                id: "preset-info-collect".into(),
                name: "信息收集".into(),
                description: "RSS 资讯、网站搜索、视频下载、GitHub 追踪".into(),
                color: "#4da7c9".into(),
                skill_ids: vec![
                    "rss-daily-digest".into(),
                    "quality-website-search".into(),
                    "video-downloader".into(),
                    "transcript-summarizer".into(),
                    "notebooklm-skill".into(),
                    "github-search".into(),
                    "github-trending".into(),
                    "baoyu-skills/skills/baoyu-url-to-markdown".into(),
                ],
                is_preset: true,
            },
        ]
    }
}
